version: '3.1'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rinha_backend
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
